
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install python to be used by ansible."
  become: true
  raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
  changed_when: false

- name: "install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present