AWSTemplateFormatVersion: 2010-09-09

Description: >-
  Description: Create a Postgres DB instance on Amazon RDS

Parameters:
  WorkflowID:
    Description: Unique identifier
    Type: String
  DBInstanceID:
    Default: bamsDB
    Description: My database instance
    Type: String
  DBName:
    Default: postgres
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.t3.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Default: '20'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.
  DBUsername:
    Default: 'postgres'
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  VPC:
    Description: Deploy the instance in this VPC
    Type: String
    Default: vpc-0784ce1583ea8b21d
  SG:
    Description: EC2 security group
    Type: String
    Default: sg-083b50aca0ae26bc2
  # Subnet:
  #   Description: This subnet must already exist
  #   Type: String
  #   Default: subnet-03eb430d72e402806
  # AZ:
  #   Description: Choose an AZ that corresponds to the Subnet in the !Subnet section
  #   Type: String
  #   Default: us-west-2c
  # LocalIPAddress:
  #   Description: This is your local IP address, it will be used to configure security group ingress
  #   Type: String
  #   Default: 0.0.0.0/0

Resources:
  Database:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      #AvailabilityZone: !Ref AZ
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: postgres
      EngineVersion: '13.4'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      Port: 5432
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref SG

Outputs:
  InstanceId:
    Description: DB Instance Id
    Value: !Ref Database
  EndpointAddress:
    Description: Endpoint Address
    Value: !GetAtt Database.Endpoint.Address
    Export:
      Name: !Sub EndpointAddress-${WorkflowID}
  EndpointPort:
    Description: Database port
    Value: !GetAtt Database.Endpoint.Port