# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

#commands:


jobs:
  job1:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo "hello world"

  create_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: create cloudformation stack
          command: |
            chmod +x ec2.sh ec2-update.sh ec2-del.sh \
            #./ec2.sh bams-${CIRCLE_WORKFLOW_ID:0:5} ec2.yml ec2.json
            aws cloudformation create-stack \
              --stack-name bams-${CIRCLE_WORKFLOW_ID:0:5} \
              --template-body file://ec2.yml \
              --parameters file://ec2.json \
              --region=us-east-1 \
            # aws cloudformation deploy \
            #   --template-file ec2.yml \
            #   --parameters ec2.json \
            #   --stack-name bams-${CIRCLE_WORKFLOW_ID:0:5} \
            #   --region us-east-1

workflows:
  # Name the workflow "welcome"
  bams_cicd:
    # Run the welcome/run job in its own container
    jobs:
      - job1
      - create_infra