---
- name: update and upgrade packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 86400

- name: remove unneeded dependencies
  become: yes
  apt:
    autoremove: yes

- name: install dependencies
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - git
    - curl
    - unzip
    - wget

# - name: Install Nodejs 13.x
#   become: true
#   shell: |
#     curl -fsSL https://deb.nodesource.com/setup_13.x | bash -
#     apt-get remove -y nodejs
#     apt-get install -y nodejs

- name: install deps
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present